#!/usr/bin/env bash
set -e


function makePattern
{
  pattern=$1

  # Convert spaces to \s
  pattern=$(echo $pattern | sed -r 's/\s+/\\s/g')

  # Convert / to \/
  pattern=$(echo $pattern | sed -r 's/\/+/\\\//g')

  echo $pattern
}

function uncomment
{
  echo uncomment $1 line in $2
  pattern=$(makePattern "$1")
  sed -i '/'$pattern'/s/^#//g' $2
}

function comment
{
  echo comment $1 line in $2
  pattern=$(makePattern "$1")
  echo '/'$pattern'/s/^/#/g'
  sed -i '/'$pattern'/s/^/#/g' $2
}


######################################
echo "Enable SSH..."
touch /ssh


######################################
echo "Enable UART..."
echo 'enable_uart=1' >> /boot/config.txt


######################################
echo "Disable system logging to GPIO serial port to free the serial port..."
sed -i 's/ console=\S*,115200//g' /boot/cmdline.txt


######################################
echo "Add serial port access to 'yadoms' user..."
sed -i 's/^dialout:x:.*:$/&yadoms/' /etc/group


######################################
echo "Set-up for PiFace2..."
uncomment 'dtparam=spi=on' /boot/config.txt


######################################
echo "Set-up for OWFS (supported by DS9490 USB dongle)..."
comment 'server: FAKE = DS18S20,DS2405' /etc/owfs.conf
uncomment 'server: usb = all' /etc/owfs.conf
uncomment 'mountpoint = /mnt/1wire' /etc/owfs.conf
uncomment 'allow_other' /etc/owfs.conf
uncomment 'user_allow_other' /etc/fuse.conf
echo "Create /mnt/1wire dir..."
mkdir /mnt/1wire
echo "Start owfs service at boot..."
update-rc.d owfs defaults
echo "Start owserver service at boot..."
update-rc.d owserver defaults


######################################
echo "Configure DHCP retry delay..."
uncomment 'retry 60;' /etc/dhcp/dhclient.conf


######################################
echo "Start Yadoms service at boot..."
sudo chown -R yadoms:yadoms /opt/yadoms/
update-rc.d yadoms defaults


######################################
echo "Localize in Europe/Paris..."
cp /usr/share/zoneinfo/Europe/Paris /etc/localtime


######################################
echo "Authorize user to shutdown..."
sudo echo '[Allow all users to shutdown and reboot]' >> /etc/polkit-1/localauthority/50-local.d/all_all_users_to_shutdown_reboot.pkla
sudo echo 'Identity=unix-user:*' >> /etc/polkit-1/localauthority/50-local.d/all_all_users_to_shutdown_reboot.pkla
sudo echo 'Action=org.freedesktop.login1.power-off;org.freedesktop.login1.power-off-multiple-sessions;org.freedesktop.login1.reboot;org.freedesktop.login1.reboot-multiple-sessions' >> /etc/polkit-1/localauthority/50-local.d/all_all_users_to_shutdown_reboot.pkla
sudo echo 'ResultAny=yes' >> /etc/polkit-1/localauthority/50-local.d/all_all_users_to_shutdown_reboot.pkla


