language: cpp
dist: trusty

sudo: required

services:
  - docker
  
before_install:
  - docker pull yadoms/build_for_raspberrypi_image
  
script:
  - docker run --privileged -e YADOMS_VERSION=${YADOMS_VERSION} -e UPLOAD_FTP_CREDENTIALS=${FTP_USER}:${FTP_PASSWORD} yadoms/build_for_raspberrypi_image
