language: generic

#TODO : trusty is too old Ubuntu distribution, so this script doesn't work for now.
#TODO : We have to wait a newer distribution (works with 17.04) to make Pi image generation from Travis.
dist: trusty
sudo: required

#limit to git depth to 1 because don't use any git command in this script
git:
  depth: 1
  

before_install:
# Installing dependancies
- echo 'Installing dependancies...'
- sudo apt-get install build-essential wget git lzop u-boot-tools binfmt-support qemu qemu-user-static multistrap parted dosfstools


script:
# Yadoms configuration file
- echo 'Start creating image...'
- sudo ./create-yadoms-pi-image ${YADOMS_VERSION}

# Yadoms configuration file
- docker pull yadoms/ubuntu_rpi_image_64

#start the docker container
- docker run --privileged --name buildvm yadoms/ubuntu_rpi_image_64 /bin/bash -c "mkdir builder;"

#copy file to container
- docker cp ./ buildvm:builder

#execute the image building
- docker exec --privileged buildvm /bin/bash -c "cd builder; ./create-yadoms-pi-image ${YADOMS_VERSION}"

#copy result
- docker cp buildvm:builder/Yadoms-${YADOMS_VERSION}-RaspberryPI.img.zip Yadoms-${YADOMS_VERSION}-RaspberryPI.img.zip


after_success:
# Upload image
- echo 'Upload image to ${YADOMS_UPLOAD_URL}...'
- curl --ftp-create-dirs -T Yadoms-${YADOMS_VERSION}-RaspberryPI.img.zip -u $FTP_USER:$FTP_PASSWORD ${YADOMS_UPLOAD_URL}

