#!/bin/bash
# file: create-yadoms-pi-image
#
set -e

function error
{
  echo
  echo "This script creates the Yadoms Pi image"
  echo "  It downloads the RaspberryPI Yadoms package and creates the image"
  echo
  echo "usage :"
  echo "  ./create-yadoms-pi-image.sh {version} [official]"
  echo
  echo "with :"
  echo "  - {version} : something like 2.0.0-rc.4"
  echo "  - [official] : if given, generate image from official Yadoms release package (from Github releases repo)"
  echo "                 if not given, generate image from temporary release package (from www.yadoms.com/travis_build/raspberry_pi)"
  echo
  exit 1
}

#Check if sudo
if [ "$(whoami)" != "root" ]; then
  echo "Sorry, you are not root"
  error
fi

if [ -z "$1" ]
then
  echo "Yadoms version is missing"
  error
else
  yadomsVersion=$1
fi

if [ -z "$2" ]
then
  echo "*** Generate a NON-OFFICIAL image ***"
  official=false
else
  echo "Generate a OFFICIAL image"
  official=true
fi

echo "Download Yadoms package..."
rm -f Yadoms-*-RaspberryPI.tar.bz2
if [ "$official" = true ]
then
   wget -O yadoms.tar.bz2 https://github.com/Yadoms/yadoms/releases/download/$yadomsVersion/Yadoms-$yadomsVersion-RaspberryPI.tar.bz2
else
   wget -U 'yadomsAgent/1.0' -O yadoms.tar.gz http://yadoms.com/travis_build/raspberry_pi/Yadoms-$yadomsVersion-Linux.tar.gz
fi

echo "Inflate Yadoms package..."
rm -rf plugins/yadoms/files/opt/yadoms
mkdir -p plugins/yadoms/files/opt/yadoms
if [ "$official" = true ]
then
   tar xjf yadoms.tar.bz2 -C plugins/yadoms/files/opt/yadoms --strip 1
   rm -f yadoms.tar.bz2
else
   tar -zxvf yadoms.tar.gz -C plugins/yadoms/files/opt/yadoms --strip 2
   rm -f yadoms.tar.gz
fi

echo "Build the image..."
rm -f *.img
rm -f *.img.zip
make

echo "Rename out file..."
imgFile=$(find . -maxdepth 1 -name "*.img")
mv $imgFile Yadoms-$yadomsVersion-RaspberryPI.img

echo "Zip image file..."
zip Yadoms-$yadomsVersion-RaspberryPI.img.zip Yadoms-$yadomsVersion-RaspberryPI.img

exit 0
