#!/bin/bash
### BEGIN INIT INFO
# Provides:          yadoms
# Required-Start:    $local_fs $remote_fs $network ntp
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Yadoms daemon
# Description:       Yadoms is an opensource domotic server solution.
### END INIT INFO

case "$1" in
    start)
        # Stop the ntp service
        sudo /etc/init.d/ntp stop
        # force the time synchronization
        sudo ntpd -q -g
        # restart the ntp service
        sudo /etc/init.d/ntp start
        # Start Yadoms as pi user
        sudo -u pi '/opt/yadoms/yadoms' --daemon

        ;;
    stop)
        # Executed commands launched with "stop" parameter (during system halt)
        killall yadoms
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
esac
exit 0
